NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: intermediatecacerts/localhost-7054.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: intermediatecacerts/localhost-7054.pem
    OrganizationalUnitIdentifier: peer
