#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ica.shipper.logistic:
    container_name: ica.shipper.logistic
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      # CONFIG Sets in fabric-ca-server-config.yaml
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw' 
    volumes:
      - ./crypto-config/peerOrganizations/shipper.logistic/ca/:/etc/hyperledger/fabric-ca-server-config # Copy MSP and call it from ENVIRONMENT
      - ./ca-config/:/etc/hyperledger/fabric-ca-server # Copy fabric-ca-server-config in fabric-ca-server
    networks:
      - basic
