version: '2'

volumes:
  intelipost.logistic:
  intelipost2.logistic:
  intelipost3.logistic:

networks:
  basic:

services:
  intelipost.logistic:
    container_name: intelipost.logistic
    restart: always
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    networks:
      - basic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/logistic/orderers/intelipost.logistic/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/logistic/orderers/intelipost.logistic/tls/:/var/hyperledger/orderer/tls
      - intelipost.logistic:/var/hyperledger/production/orderer # i. chains/ ii. index/ => These two folders are required to recreate the orderer.
    ports:
      - 7050:7050
      
  intelipost2.logistic:
    container_name: intelipost2.logistic
    restart: always
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    networks:
      - basic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/logistic/orderers/intelipost2.logistic/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/logistic/orderers/intelipost2.logistic/tls/:/var/hyperledger/orderer/tls
      - intelipost2.logistic:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  intelipost3.logistic:
    container_name: intelipost3.logistic
    restart: always
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    networks:
      - basic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/logistic/orderers/intelipost3.logistic/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/logistic/orderers/intelipost3.logistic/tls/:/var/hyperledger/orderer/tls
      - intelipost3.logistic:/var/hyperledger/production/orderer
    ports:
      - 9050:7050
