NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: intermediatecacerts/ORG_ICA_CERT_NAME
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: intermediatecacerts/ORG_ICA_CERT_NAME
    OrganizationalUnitIdentifier: peer
